# -*- coding: utf-8 -*-
"""Daulab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ERos85yan5GmkK6twiH2_ehXEiJovF5
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, callbacks
import numpy as np
import math

# --- 1. 加载并预处理 MNIST ---
(x_train_full, y_train_full), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train_full = x_train_full.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# 划分 validation
x_valid, x_train = x_train_full[:5000], x_train_full[5000:]
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]

# flatten + one-hot
x_train = x_train.reshape((-1, 28*28))
x_valid = x_valid.reshape((-1, 28*28))
x_test  = x_test.reshape((-1, 28*28))

y_train_cat = keras.utils.to_categorical(y_train, 10)
y_valid_cat = keras.utils.to_categorical(y_valid, 10)
y_test_cat  = keras.utils.to_categorical(y_test, 10)

# --- 2. 定义模型架构 ---
def build_model():
    model = keras.models.Sequential([
        layers.InputLayer(input_shape=(28*28,)),
        layers.Dense(300, activation="relu"),
        layers.Dense(100, activation="relu"),
        layers.Dense(10,  activation="softmax"),
    ])
    return model

# --- 3. 找 optimal learning rate: 使用 lr range test ---
class LRFinder(callbacks.Callback):
    def __init__(self, start_lr=1e-5, end_lr=10, num_it=100):
        super().__init__()
        self.start_lr = start_lr
        self.end_lr = end_lr
        self.num_it = num_it
        self.iteration = 0
        self.lrs = []
        self.losses = []
    def on_train_batch_begin(self, batch, logs=None):
        lr = self.start_lr * (self.end_lr / self.start_lr) ** (self.iteration / self.num_it)
        # Fix: Access the learning_rate attribute of the optimizer and use .assign()
        self.model.optimizer.learning_rate.assign(lr)
        self.lrs.append(lr)
        self.iteration += 1
    def on_train_batch_end(self, batch, logs=None):
        self.losses.append(logs["loss"])

# 构建模型 & 编译
model = build_model()
model.compile(
    optimizer=keras.optimizers.SGD(learning_rate=1e-5),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

lr_finder = LRFinder(start_lr=1e-3, end_lr=10, num_it=2000)
history = model.fit(
    x_train, y_train_cat,
    batch_size=128,
    epochs=1,
    callbacks=[lr_finder],
    validation_data=(x_valid, y_valid_cat),
    shuffle=True
)

# 保存 lr vs loss 的数据
import matplotlib.pyplot as plt
plt.plot(lr_finder.lrs, lr_finder.losses)
plt.xscale("log")
plt.xlabel("Learning rate")
plt.ylabel("Training loss")
plt.show()

# 观察曲线，找 loss 开始剧增 (diverge) 的 lr — 假设比如 lr ≈ 0.1 是边界

# --- 4. 用选好的 lr 训练 + TensorBoard + EarlyStopping/Checkpoint ---
best_lr = 0.05  # 假设通过上图决定

model = build_model()
model.compile(
    optimizer=keras.optimizers.SGD(learning_rate=best_lr),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

logdir = "logs/mnist_mlp"
tensorboard_cb = callbacks.TensorBoard(log_dir=logdir)
earlystop_cb = callbacks.EarlyStopping(patience=5, restore_best_weights=True)
checkpoint_cb = callbacks.ModelCheckpoint("best_mnist_mlp.h5", save_best_only=True)

history = model.fit(
    x_train, y_train_cat,
    epochs=50,
    validation_data=(x_valid, y_valid_cat),
    callbacks=[tensorboard_cb, earlystop_cb, checkpoint_cb],
    batch_size=128,
    shuffle=True
)

test_loss, test_acc = model.evaluate(x_test, y_test_cat)
print("Test accuracy:", test_acc)

# Commented out IPython magic to ensure Python compatibility.
logdir = "logs/mnist_mlp"
# %load_ext tensorboard
# %tensorboard --logdir {logdir}

"""This will start the TensorBoard server, and you'll see an interactive dashboard in your Colab output that allows you to monitor metrics, visualize graphs, and inspect other aspects of your training run."""

import tensorflow as tf
from tensorflow.keras import layers, models, initializers

# =============================
# 1. 加载 Fashion MNIST 数据集
# =============================
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

# 归一化到 [0,1]
x_train = x_train.reshape(-1, 28 * 28) / 255.0
x_test = x_test.reshape(-1, 28 * 28) / 255.0

# =============================
# 2. 构建 100 层 DNN
# =============================
def build_model(activation):
    model = models.Sequential()
    model.add(layers.Input(shape=(784,)))

    for _ in range(100):
        model.add(
            layers.Dense(
                100,
                activation=activation,
                kernel_initializer="he_normal"
            )
        )

    model.add(layers.Dense(10, activation="softmax"))
    return model

# =============================
# 3. 训练不同激活函数的模型
# =============================
activations = ["sigmoid", "relu", "elu", "selu"]

for act in activations:
    print(f"\n===== Training with {act.upper()} =====")

    model = build_model(act)
    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    model.fit(
        x_train, y_train,
        epochs=10,
        batch_size=64,
        validation_split=0.1
    )

    test_loss, test_acc = model.evaluate(x_test, y_test)
    print(f"{act.upper()} Test Accuracy: {test_acc:.4f}")

import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, optimizers

# =============================
# 1. 加载 CIFAR-10 数据集
# =============================
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

# 将图像拉平成向量（因为这是 DNN，不是 CNN）
x_train = x_train.reshape(-1, 32 * 32 * 3) / 255.0
x_test = x_test.reshape(-1, 32 * 32 * 3) / 255.0

# =============================
# 2. 构建 20 层深度 DNN
# =============================
def build_dnn(use_bn=False):
    model = models.Sequential()
    model.add(layers.Input(shape=(3072,)))

    for _ in range(20):  # 20 个隐藏层
        model.add(
            layers.Dense(
                100,              # 每层 100 个神经元
                activation="elu",        # ELU 激活函数
                kernel_initializer="he_normal"  # He 初始化
            )
        )
        if use_bn:
            model.add(layers.BatchNormalization())

    model.add(layers.Dense(10, activation="softmax"))  # 10 类输出
    return model

# =============================
# 3. Early Stopping
# =============================
early_stop = callbacks.EarlyStopping(
    patience=5,
    restore_best_weights=True
)

# =============================
# 4. 不同优化器实验
# =============================
optimizers_dict = {
    "SGD": optimizers.SGD(learning_rate=0.01),
    "Momentum": optimizers.SGD(learning_rate=0.01, momentum=0.9),
    "NAG": optimizers.SGD(learning_rate=0.01, momentum=0.9, nesterov=True),
    "AdaGrad": optimizers.Adagrad(learning_rate=0.01),
    "RMSProp": optimizers.RMSprop(learning_rate=0.001),
    "Adam": optimizers.Adam(learning_rate=0.001),
    "Nadam": optimizers.Nadam(learning_rate=0.001),
}

# =============================
# 5. 训练并比较不同优化器
# =============================
for name, opt in optimizers_dict.items():
    print(f"\n===== Training with {name} =====")

    model = build_dnn(use_bn=False)

    model.compile(
        optimizer=opt,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    model.fit(
        x_train, y_train,
        epochs=50,
        batch_size=64,
        validation_split=0.1,
        callbacks=[early_stop],
        verbose=2
    )

    test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
    print(f"{name} Test Accuracy: {test_acc:.4f}")

# =============================
# 6. 加 Batch Normalization 再训练（用 Nadam）
# =============================
print("\n===== Training with Batch Normalization =====")

model_bn = build_dnn(use_bn=True)

model_bn.compile(
    optimizer=optimizers.Nadam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model_bn.fit(
    x_train, y_train,
    epochs=50,
    batch_size=64,
    validation_split=0.1,
    callbacks=[early_stop],
    verbose=2
)

model_bn.evaluate(x_test, y_test)

